### ISSUE TITLE
[Suggestion] dxvk port?

### ISSUE THREAD

**Issue by PainedPsyche** [keretus/sfe#4]
Since this mod overrides dxgi.dll, it directly conflicts with dxvk and therefore cannot be used when playing on Linux. Any chance this could be ported, so that Linux players can enjoy F76 text chat mod as well?

**Comment by PainedPsyche** [comment]
It seems this actually works fine with dxvk (which is very counterintuitive). This issue is pointless, disregard it.

**Comment by jgentil** [comment]
Can I ask how you got SFE and DXVK running together?  they both override dxgi.dll so I didn't think they could work together.
